(function (global) {
    let ajax_utils = {};

    // If a request is generated by the client (our browser) then a new request object is created
    function get_request_object() {
        if (window.XMLHttpRequest){
            return (new XMLHttpRequest())
        }
    }

    ajax_utils.send_GET_request = function (required_url, response_handler, isJSONResponse) {
        let request = get_request_object();
        request.open("GET", required_url, true);
        request.send();


        function handle_response(request, response_handler, isJSONResponse) {
            if ((request.readyState === 4) && (request.status === 200)){
                response_handler(request);
            }

            if (isJSONResponse === undefined){
                isJSONResponse = true;
            }

            if (isJSONResponse){
                response_handler(JSON.parse(request.responseText))
            }
            else {
                response_handler(request)
            }
        }


        request.onreadystatechange = function () {
            handle_response(request, response_handler, isJSONResponse);
        };
    };
    global.$ajax_utils = ajax_utils;
})(window);
